// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGylj63d-nO-w0ciY3Ug9UGdIivqyL2-E',
    appId: '1:488481524068:web:334f9ac27a004a9a6e1271',
    messagingSenderId: '488481524068',
    projectId: 'mamatender-cf27f',
    authDomain: 'mamatender-cf27f.firebaseapp.com',
    databaseURL: 'https://mamatender-cf27f-default-rtdb.firebaseio.com',
    storageBucket: 'mamatender-cf27f.appspot.com',
    measurementId: 'G-ETN0JN65CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWsCsgv6QH65WV667KG9cH8WR0ZU0cZ0',
    appId: '1:488481524068:android:9dc1ca83a31b2d566e1271',
    messagingSenderId: '488481524068',
    projectId: 'mamatender-cf27f',
    databaseURL: 'https://mamatender-cf27f-default-rtdb.firebaseio.com',
    storageBucket: 'mamatender-cf27f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwvRcfaBrhiq1Hx3cnwkjVJJAAtoeouA',
    appId: '1:488481524068:ios:2cabbf0c9ee531036e1271',
    messagingSenderId: '488481524068',
    projectId: 'mamatender-cf27f',
    databaseURL: 'https://mamatender-cf27f-default-rtdb.firebaseio.com',
    storageBucket: 'mamatender-cf27f.appspot.com',
    androidClientId: '488481524068-ebqpaa8rehs775n53tp3no0qh7urmfb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFwvRcfaBrhiq1Hx3cnwkjVJJAAtoeouA',
    appId: '1:488481524068:ios:37a4720cf33a62ff6e1271',
    messagingSenderId: '488481524068',
    projectId: 'mamatender-cf27f',
    databaseURL: 'https://mamatender-cf27f-default-rtdb.firebaseio.com',
    storageBucket: 'mamatender-cf27f.appspot.com',
    androidClientId: '488481524068-ebqpaa8rehs775n53tp3no0qh7urmfb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrtask.RunnerTests',
  );
}
